// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4_aESiKMH-l-Zwj8mhWQo9C_DimMBmDY',
    appId: '1:207007848066:web:46a06881f9ae5ae787869b',
    messagingSenderId: '207007848066',
    projectId: 'monthly-expense-634ae',
    authDomain: 'monthly-expense-634ae.firebaseapp.com',
    storageBucket: 'monthly-expense-634ae.firebasestorage.app',
    measurementId: 'G-RJN3NFMHSS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpDzIxVQhPh6cVjJSpTv3K-DrwHQ2kni4',
    appId: '1:207007848066:android:0f781d7c84f7ea7a87869b',
    messagingSenderId: '207007848066',
    projectId: 'monthly-expense-634ae',
    storageBucket: 'monthly-expense-634ae.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUS8DmYknPbHkal5ZhMgLHKeKh81GfGho',
    appId: '1:207007848066:ios:6765c451700f8a1987869b',
    messagingSenderId: '207007848066',
    projectId: 'monthly-expense-634ae',
    storageBucket: 'monthly-expense-634ae.firebasestorage.app',
    iosBundleId: 'com.example.monthlyExpenseFlutterProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUS8DmYknPbHkal5ZhMgLHKeKh81GfGho',
    appId: '1:207007848066:ios:6765c451700f8a1987869b',
    messagingSenderId: '207007848066',
    projectId: 'monthly-expense-634ae',
    storageBucket: 'monthly-expense-634ae.firebasestorage.app',
    iosBundleId: 'com.example.monthlyExpenseFlutterProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4_aESiKMH-l-Zwj8mhWQo9C_DimMBmDY',
    appId: '1:207007848066:web:eb9655faaba5e08087869b',
    messagingSenderId: '207007848066',
    projectId: 'monthly-expense-634ae',
    authDomain: 'monthly-expense-634ae.firebaseapp.com',
    storageBucket: 'monthly-expense-634ae.firebasestorage.app',
    measurementId: 'G-DMGKZC4MQP',
  );
}
